services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: jyothiram266/ollama-langchain:v1
    ports:
      - 8501:8501