apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama-container
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
    - protocol: TCP
      port: 8501
      targetPort: 8501
  