apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-container
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: ollama-container
  template:
    metadata:
      labels:
        app: ollama-container
    spec:
      containers:
      - name: ollama-container
        image: ollama/ollama
        ports:
        - containerPort: 8501
        - containerPort: 11434
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama  # Mount path inside the container
      volumes:
      - name: ollama-data
        emptyDir: {}  # Define emptyDir volume